# Generated by Django 4.0.7 on 2022-11-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
    ]
